FROM n8nio/n8n:latest

USER root

ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV NODE_ENV=production
ENV EXECUTIONS_PROCESS=main
ENV N8N_ENCRYPTION_KEY=xK9mP2qL7nR4vT8w3jB6
ENV N8N_RUNNERS_ENABLED=false

EXPOSE 5678

CMD ["n8n", "start"]
